<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ArticleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $articles = [
            [
                'reference' => '04465-35290',
                'name' => "Plaquette frein AV Hilux/Fortuner",
                'description' => "Plaquette frein AV Hilux/Fortuner",
                'article_category_id' => 1,
                'brand' => 'HILUX',
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 2,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => '04465-BZ250',
                'name' => "Plaquette frein AV Suzuki/RUNION",
                'description' => "Plaquette frein AV Suzuki/RUNION",
                'article_category_id' => 1,
                'brand' => 'SUZUKI',
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 40,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => '04466-YZZAM',
                'name' => "Plaquette frein AR Fortuner",
                'description' => "Plaquette frein AR Fortuner",
                'article_category_id' => 1,
                'brand' => 'FORTUNER',
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 16,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => '04466-60020',
                'name' => "Plaquette frein AR Fortuner",
                'description' => "Plaquette frein AR Fortuner",
                'article_category_id' => 1,
                'brand' => 'FORTUNER',
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 8,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => '04466-60440',
                'name' => "Plaquette frein AR Fortuner",
                'description' => "Plaquette frein AR Fortuner",
                'article_category_id' => 1,
                'brand' => 'FORTUNER',
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 8,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'MZ696572',
                'name' => "Plaquette frein AV Mitsubishi",
                'description' => "Plaquette frein AV Mitsubishi",
                'article_category_id' => 1,
                'brand' => 'MITSUBISHI',
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 2,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => '04465-BZ170',
                'name' => "Plaquette frein AV AVANZA",
                'description' => "Plaquette frein AV AVANZA",
                'article_category_id' => 1,
                'brand' => 'AVANZA',
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 2,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => '3008',
                'name' => "Plaquette frein AV 3008 Speed Tel",
                'description' => "Plaquette frein AV 3008 Speed Tel",
                'article_category_id' => 1,
                'brand' => null,
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 2,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'CD-5187',
                'name' => "Plaquette frein AV 3008 BER",
                'description' => "Plaquette frein AV 3008 BER",
                'article_category_id' => 1,
                'brand' => null,
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 4,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'KD2482',
                'name' => "Plaquette frein AR Corolla ASIMCO",
                'description' => "Plaquette frein AR Corolla ASIMCO",
                'article_category_id' => 1,
                'brand' => 'COROLLA',
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 2,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'KD 2088',
                'name' => "Plaquette frein AV Corolla ASIMCO",
                'description' => "Plaquette frein AV Corolla ASIMCO",
                'article_category_id' => 1,
                'brand' => 'COROLLA',
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 2,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'D2228 (BRAKE PAD)',
                'name' => "Plaquette frein AV PRADO Hilux",
                'description' => "Plaquette frein AV PRADO Hilux",
                'article_category_id' => 1,
                'brand' => 'HILUX',
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 4,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'D2228 (GACELN)',
                'name' => "Plaquette frein AV PRADO-Hilux",
                'description' => "Plaquette frein AV PRADO-Hilux",
                'article_category_id' => 1,
                'brand' => 'HILUX',
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 2,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'CD6445 (BON VOYAGE) (MABENG)',
                'name' => "Plaquette frein AV CIVILIAN",
                'description' => "Plaquette frein AV CIVILIAN",
                'article_category_id' => 1,
                'brand' => 'CIVILIAN',
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 4,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'Divers',
                'name' => "Plaquette frein AV Sous carton ASIMCO",
                'description' => "Plaquette frein AV Sous carton ASIMCO",
                'article_category_id' => 1,
                'brand' => 'ASIMCO',
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 12,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => '04495-35250',
                'name' => "Garniture de frein AR Hilux",
                'description' => "Garniture de frein AR Hilux",
                'article_category_id' => 2,
                'brand' => 'HILUX',
                'model' => null,
                'unit' => 'carton',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 20,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'F2025 (FITWELL)',
                'name' => "Garniture de frein AR Hilux",
                'description' => "Garniture de frein AR Hilux",
                'article_category_id' => 2,
                'brand' => 'HILUX',
                'model' => null,
                'unit' => 'carton',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 14,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'HAINS 3/4''DR',
                'name' => "Compresseur ou pistolet à boullons pneumatique",
                'description' => "Compresseur ou pistolet à boullons pneumatique",
                'article_category_id' => 4,
                'brand' => null,
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 2,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => '31250-OK440',
                'name' => "Disque d'embrayage Hilux",
                'description' => "Disque d'embrayage Hilux",
                'article_category_id' => 3,
                'brand' => 'HILUX',
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 2,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => '31210-OK420',
                'name' => "Plateau d'embrayage Hilux",
                'description' => "Plateau d'embrayage Hilux",
                'article_category_id' => 3,
                'brand' => 'HILUX',
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 2,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => '43568-59175',
                'name' => "Garniture de distribution Hilux courroies accessoire Hilux",
                'description' => "Garniture de distribution Hilux courroies accessoire Hilux",
                'article_category_id' => 11,
                'brand' => 'HILUX',
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 4,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'ART-0022',
                'name' => "Article 22",
                'description' => "",
                'article_category_id' => 11,
                'brand' => null,
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 12,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'Scie à métaux',
                'name' => "Scie à métaux",
                'description' => "Scie à métaux",
                'article_category_id' => 8,
                'brand' => null,
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 6,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'M40A1208 (BOSTAMANN 26-25)',
                'name' => "Compresseur d'air pour pneus",
                'description' => "Compresseur d'air pour pneus",
                'article_category_id' => 4,
                'brand' => null,
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 8,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'M40A1200 (HEAVY DUTY)',
                'name' => "Compresseur d'air pour pneus",
                'description' => "Compresseur d'air pour pneus",
                'article_category_id' => 4,
                'brand' => null,
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 4,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'ROCKY FE (K+F)',
                'name' => "Siren ROCKY FE",
                'description' => "Siren ROCKY FE",
                'article_category_id' => 11,
                'brand' => 'ROCKY',
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 4,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'HELLA',
                'name' => "Klaxon HELLA",
                'description' => "Klaxon HELLA",
                'article_category_id' => 11,
                'brand' => 'HELLA',
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 2,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'HANS',
                'name' => "Musicuse accordéon",
                'description' => "Musicuse accordéon",
                'article_category_id' => 11,
                'brand' => 'HANS',
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 2,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'côté gauche',
                'name' => "Pot de feu rouge AR Hilux Gauche",
                'description' => "Pot de feu rouge AR Hilux Gauche",
                'article_category_id' => 5,
                'brand' => 'HILUX',
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 16,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'côté droit',
                'name' => "Pot de feu rouge AR Hilux Droit",
                'description' => "Pot de feu rouge AR Hilux Droit",
                'article_category_id' => 5,
                'brand' => 'HILUX',
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 2,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'côté gauche',
                'name' => "Pot de phare AV Hilux Gauche",
                'description' => "Pot de phare AV Hilux Gauche",
                'article_category_id' => 5,
                'brand' => 'HILUX',
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 12,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'côté droit',
                'name' => "Pot de phare AV Hilux droit",
                'description' => "Pot de phare AV Hilux droit",
                'article_category_id' => 5,
                'brand' => 'HILUX',
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 6,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'HANS 3/4',
                'name' => "Coffre à douilles HANS",
                'description' => "Coffre à douilles HANS",
                'article_category_id' => 8,
                'brand' => 'HANS',
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 2,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'Compressiomètre',
                'name' => "Coffret à compressiomètre",
                'description' => "Coffret à compressiomètre",
                'article_category_id' => 8,
                'brand' => null,
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 4,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'K7 Premium Power',
                'name' => "Karcher K7 Premium Power",
                'description' => "Karcher K7 Premium Power",
                'article_category_id' => 9,
                'brand' => null,
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 2,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'AMERICAN YK-816',
                'name' => "Pince à soudure (Positif)",
                'description' => "Pince à soudure (Positif)",
                'article_category_id' => 8,
                'brand' => 'AMERICAN',
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 12,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'WISEUR ART. 41C101',
                'name' => "Pince à soudure (Positif)",
                'description' => "Pince à soudure (Positif)",
                'article_category_id' => 8,
                'brand' => 'WISEUR',
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 8,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'HOLLAN TYPE',
                'name' => "Pince à soudure (Négatif)",
                'description' => "Pince à soudure (Négatif)",
                'article_category_id' => 8,
                'brand' => 'HOLLAN',
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 4,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'EARTH CLAMP',
                'name' => "Pince à soudure (Négatif) masq",
                'description' => "Pince à soudure (Négatif) masq",
                'article_category_id' => 8,
                'brand' => 'EARTH',
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 4,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'BAB258-1-P',
                'name' => "Mini poste à soudure Boster",
                'description' => "Mini poste à soudure Boster",
                'article_category_id' => 10,
                'brand' => 'BOSTER',
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 2,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'WISELIF(ART.17C508)',
                'name' => "Mini poste à soudure WISELIF",
                'description' => "Mini poste à soudure WISELIF",
                'article_category_id' => 10,
                'brand' => 'WISELIF',
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 4,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'BIG RED',
                'name' => "Aspirateur de vidange",
                'description' => "Aspirateur de vidange",
                'article_category_id' => 15,
                'brand' => 'BIG RED',
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 2,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'Bache pour véhicule',
                'name' => "Bache pour véhicule",
                'description' => "Bache pour véhicule",
                'article_category_id' => 11,
                'brand' => null,
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 16,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'SAGA OCTOPUS',
                'name' => "Alarmes Octopus Saga",
                'description' => "Alarmes Octopus Saga",
                'article_category_id' => 6,
                'brand' => 'SAGA',
                'model' => null,
                'unit' => 'carton',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 40,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'SAGA OCTOPUS',
                'name' => "Alarme Octopus Saga",
                'description' => "Alarme Octopus Saga",
                'article_category_id' => 6,
                'brand' => 'SAGA',
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 10,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'BRAVO',
                'name' => "Alarme Bravo",
                'description' => "Alarme Bravo",
                'article_category_id' => 6,
                'brand' => 'BRAVO',
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 2,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'ROYAL BEMAZ',
                'name' => "Alarme ROYAL BEMAZ",
                'description' => "Alarme ROYAL BEMAZ",
                'article_category_id' => 6,
                'brand' => 'BEMAZ',
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 2,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'TOYOTA',
                'name' => "Alarme TOYOTA",
                'description' => "Alarme TOYOTA",
                'article_category_id' => 6,
                'brand' => 'TOYOTA',
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 12,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'TOTAL MULTIS',
                'name' => "Pots de graisse MULTIS TOTAL 1Kg",
                'description' => "Pots de graisse MULTIS TOTAL 1Kg",
                'article_category_id' => 7,
                'brand' => 'TOTAL',
                'model' => null,
                'unit' => 'kg',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 32,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'ROBOT MAGIC',
                'name' => "Mini Karcher Robot magic",
                'description' => "Mini Karcher Robot magic",
                'article_category_id' => 9,
                'brand' => 'ROBOT',
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 12,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'Mini Karcher',
                'name' => "Mini Karcher",
                'description' => "Mini Karcher",
                'article_category_id' => 9,
                'brand' => null,
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 42,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'Jent alu',
                'name' => "Jante alu",
                'description' => "Jante alu",
                'article_category_id' => 17,
                'brand' => null,
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 8,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'Total Wash',
                'name' => "Flacon de 400ml Total Wash",
                'description' => "Flacon de 400ml Total Wash",
                'article_category_id' => 9,
                'brand' => 'TOTAL',
                'model' => null,
                'unit' => 'litre',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 22,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'Chainlub Total',
                'name' => "Aérosol décappant Total",
                'description' => "Aérosol décappant Total",
                'article_category_id' => 9,
                'brand' => 'TOTAL',
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 10,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'RPG4',
                'name' => "Bloc-volant de sécurité",
                'description' => "Bloc-volant de sécurité",
                'article_category_id' => 11,
                'brand' => null,
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 16,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'CC Legend',
                'name' => "Bloc-volant CC Legend",
                'description' => "Bloc-volant CC Legend",
                'article_category_id' => 11,
                'brand' => null,
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 2,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'Good Luck',
                'name' => "Bloc-volant Good Luck",
                'description' => "Bloc-volant Good Luck",
                'article_category_id' => 11,
                'brand' => null,
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 2,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'NATIONAL PAINTS',
                'name' => "Pot de mastic National",
                'description' => "Pot de mastic National",
                'article_category_id' => 11,
                'brand' => null,
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 2,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'ART-0059',
                'name' => "Paire de gant en caoutchouc",
                'description' => "Paire de gant en caoutchouc",
                'article_category_id' => 20,
                'brand' => null,
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 2,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'ART-0060',
                'name' => "Chariot porte-bouteille",
                'description' => "Chariot porte-bouteille",
                'article_category_id' => 15,
                'brand' => null,
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 2,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'AIRGAZ',
                'name' => "Bouteille d'oxygène",
                'description' => "Bouteille d'oxygène",
                'article_category_id' => 20,
                'brand' => 'AIRGAZ',
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 2,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'AIRGAZ',
                'name' => "Bouteille d'acétylène",
                'description' => "Bouteille d'acétylène",
                'article_category_id' => 20,
                'brand' => 'AIRGAZ',
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 2,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'Total',
                'name' => "Anti-fuite radiateur Total flacon de 300ml",
                'description' => "Anti-fuite radiateur Total flacon de 300ml",
                'article_category_id' => 7,
                'brand' => 'TOTAL',
                'model' => null,
                'unit' => 'litre',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 24,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'SIM GLASS',
                'name' => "Savon liquide pour vitre Sim Classe 750ml",
                'description' => "Savon liquide pour vitre Sim Classe 750ml",
                'article_category_id' => 7,
                'brand' => 'SIM',
                'model' => null,
                'unit' => 'litre',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 30,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'BENCH VICE 8''',
                'name' => "Etau TOTAL",
                'description' => "Etau TOTAL",
                'article_category_id' => 15,
                'brand' => 'TOTAL',
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 2,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'TOYOTA COROLLA',
                'name' => "Disque avant TOYOTA COROLLA",
                'description' => "Disque avant TOYOTA COROLLA",
                'article_category_id' => 14,
                'brand' => 'TOYOTA',
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 2,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'TOYOTA COROLLA',
                'name' => "Disque ARRIERE Corolla",
                'description' => "Disque ARRIERE Corolla",
                'article_category_id' => 14,
                'brand' => 'TOYOTA',
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 8,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'FINDER 461A',
                'name' => "Pistolet à peinture pneumatique Eang",
                'description' => "Pistolet à peinture pneumatique Eang",
                'article_category_id' => 4,
                'brand' => 'FINDER',
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 2,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'PONSA EN12195-2:2000',
                'name' => "Sangle de remorquage 5m",
                'description' => "Sangle de remorquage 5m",
                'article_category_id' => 18,
                'brand' => 'PONSA',
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 2,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => '7C40C',
                'name' => "Rivet 6x40mm",
                'description' => "Rivet 6x40mm",
                'article_category_id' => 19,
                'brand' => null,
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 2,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => '7C40C',
                'name' => "Rivet 6.4x40mm",
                'description' => "Rivet 6.4x40mm",
                'article_category_id' => 19,
                'brand' => null,
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 4,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'ART-0072',
                'name' => "Rivet 3.2x 9.6mm",
                'description' => "Rivet 3.2x 9.6mm",
                'article_category_id' => 19,
                'brand' => null,
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 2,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'ART-0073',
                'name' => "Disque dure ordinateur Clavier",
                'description' => "Disque dure ordinateur Clavier",
                'article_category_id' => 11,
                'brand' => null,
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 2,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'ART-0074',
                'name' => "Article 74",
                'description' => "",
                'article_category_id' => 11,
                'brand' => null,
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 2,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => '85212-0P030',
                'name' => "Balai d'essui glace Toyota moyen",
                'description' => "Balai d'essui glace Toyota moyen",
                'article_category_id' => 12,
                'brand' => 'TOYOTA',
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 12,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'Gerven',
                'name' => "Balai d'essui glace Toyota court",
                'description' => "Balai d'essui glace Toyota court",
                'article_category_id' => 12,
                'brand' => 'TOYOTA',
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 12,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'BK 3458C10',
                'name' => "Amortisseur Civilian",
                'description' => "Amortisseur Civilian",
                'article_category_id' => 13,
                'brand' => 'CIVILIAN',
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 4,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'B1662C/4C/1-',
                'name' => "Feu Arrière gauche droite Coaster",
                'description' => "Feu Arrière gauche droite Coaster",
                'article_category_id' => 5,
                'brand' => 'COASTER',
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 4,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'FACOM',
                'name' => "Clé à pipe et N° 30 27 24 21 19 18 16 15 13 16 9 8",
                'description' => "Clé à pipe et N° 30 27 24 21 19 18 16 15 13 16 9 8",
                'article_category_id' => 8,
                'brand' => 'FACOM',
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 2,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'ULTRA',
                'name' => "Clé à pans multiples 122-31",
                'description' => "Clé à pans multiples 122-31",
                'article_category_id' => 8,
                'brand' => 'ULTRA',
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 2,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'ULTRA',
                'name' => "Clé à pans multiples 122-22",
                'description' => "Clé à pans multiples 122-22",
                'article_category_id' => 8,
                'brand' => 'ULTRA',
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 4,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'BETA 42 Mob FACOM Mob',
                'name' => "Clé mix à pans fermé N° 32 30 27 24 22 21",
                'description' => "Clé mix à pans fermé N° 32 30 27 24 22 21",
                'article_category_id' => 8,
                'brand' => 'FACOM',
                'model' => null,
                'unit' => 'unité',
                'purchase_price' => null,
                'selling_price' => null,
                'min_stock_level' => 1,
                'max_stock_level' => 4,
                'tire_size' => null,
                'compatible_vehicle_categories' => null,
                'photo_path' => null,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];

        DB::table('articles')->insert($articles);
    }
}